apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-webapp-deployment
  labels:
    app: fastapi-webapp
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: fastapi-webapp-container
          image: quay.io/rugomez/fastapi-argocd-workshop:dev-0785a7bbab1a8d1551242205305b4cfda3fcec16
